# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      package_name:
        description: "用于特殊编译的包名（如 com.xxx.yyy）；留空则走普通流程"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 1) 环境安装
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y apktool signapk openjdk-8-jdk
        sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
        java -version
        javac -version

    # 2) 赋予脚本执行权限（关键修复）
    - name: Make scripts executable
      run: chmod +x build.sh mybv/java/build.sh

    # 3) 反编译（仅第一次）
    - name: Decompile
      run: |
        if [ ! -d mybv ]; then
          ./build.sh -d
        fi

    # 4) 编译
    - name: Build APK
      run: |
        if [ -n "${{ github.event.inputs.package_name }}" ]; then
          echo "Special build with package: ${{ github.event.inputs.package_name }}"
          ./build.sh -s "${{ github.event.inputs.package_name }}"
        else
          echo "Normal build"
          ./build.sh
        fi

    # 5) 整理产物
    - name: Collect artifacts
      run: |
        mkdir -p final
        cp -f mybv.apk  final/
        cp -f update.json final/

    # 6) 上传
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: final/
